[Agregar validación de precondiciones...] Guava preconditions implementation
wolox-training/jm-java pull request #10
Opened 2020-04-27 22:53 UTC by jhonmunoz

## Summary

Adds Guava for precondition validations on models

## Trello Card
https://trello.com/c/Ko1ZhSes/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

2020-04-28 16:36 UTC, rabinovichm requested changes
Add validations according to the [books](https://trello.com/c/BbeRyYdW/14-crear-modelo-de-book) and [users](https://trello.com/c/J9kZfwst/19-crear-modelo-de-user) model. For example, a book cannot have less than 1 page.

2020-04-29 18:12 UTC, rodrigofranc requested changes
All strings should be validate for not be blank

2020-04-29 18:12 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/User.java
> +    public void setBirthDate(final LocalDate birthDate) { this.birthDate = checkNotNull(birthDate); }
It should be before now

2020-04-30 15:39 UTC, rodrigofranc requested changes
Add validation for empty string in setters

2020-05-01 23:45 UTC, rodrigofranc approved these changes

2020-05-04 14:32 UTC, rabinovichm approved these changes

2020-05-04 17:19 UTC, merged