[JUnit Testing] Unit Testing for Controllers and Models
wolox-training/jm-java pull request #12
Opened 2020-04-30 17:30 UTC by jhonmunoz

## Summary 

Unit tests for user and books controllers and models

## Trello Card

https://trello.com/c/JvA2eLis/28-junit-testing

2020-05-05 22:15 UTC, rodrigofranc requested changes
Add test for BookAlreadyOwnedException

2020-05-05 22:15 UTC, rodrigofranc commented on src/test/java/com/wolox/training/controllers/BookControllerTest.java
> +    public void givenValidBook_whenUpdatesBook_thenReturnsAccepted() throws Exception {
Add test when you update book but the id is wrong, for check `BookIdMismatchException`

2020-05-05 22:15 UTC, rodrigofranc commented on src/test/java/com/wolox/training/controllers/UserControllerTest.java
> +    public void givenValidUser_whenUpdatesUser_thenReturnsAccepted() throws Exception {
Same here, add one test to check `UserIdMismatchException`

2020-05-07 19:16 UTC, rabinovichm requested changes

2020-05-07 19:16 UTC, rabinovichm commented on src/test/java/com/wolox/training/controllers/BookControllerTest.java
> +    public void givenValidBook_whenDeletesBook_thenReturnsNoContent() throws Exception {
You could also add a test for the case in which someone wants to delete a book that is not present on the DB.

2020-05-07 19:16 UTC, rabinovichm commented on src/test/java/com/wolox/training/controllers/UserControllerTest.java
> +    public void givenValidUser_whenDeletesUser_thenReturnsNoContent() throws Exception {
Same here, it would be nice to have a test to check that the "not found" exception is thrown when necessary

2020-05-07 19:16 UTC, rabinovichm commented on src/test/java/com/wolox/training/controllers/UserControllerTest.java
> +    public void givenAuthor_whenFindTopByName_thenReturnsJson() throws Exception {
What happens if no user is found with the passed name? 🤔(I'm really asking, but having a test for that would have answered it 😋). Is the current behaviour what you expected to be?

2020-05-07 19:19 UTC, rabinovichm reviewed
I assume you know this, but it's never wrong to have a reminder. Besides assuring that everything works properly when changes are made in the code, tests also help understanding and knowing the proper behaviour of the app.

2022-10-14 15:45 UTC, closed without merging