[Crear modelo de User] User Model implentation
wolox-training/jm-java pull request #6
Opened 2020-04-22 15:50 UTC by jhonmunoz

## Summary

- User Model implementation (OneToMany relationship to Books)
- Exception handling

## Trello Card

https://trello.com/c/J9kZfwst/19-crear-modelo-de-user

2020-04-23 00:41 UTC, rodrigofranc requested changes

2020-04-23 00:41 UTC, rodrigofranc commented on src/main/java/com/wolox/training/repositories/UserRepository.java
> +public interface UserRepository extends CrudRepository<Book, Long> {
This repo is not necessary yet

2020-04-23 00:41 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/Book.java
> +    @ManyToMany(mappedBy = "books", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
`cascade` option is not necessary here

2020-04-23 00:41 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/User.java
> +    @JoinTable(name = "book_user",
@JoinTable is not required here, in @manytomany relationships JPA do this work for you

2020-04-23 00:41 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/User.java
> +        if (getBooks().contains(book)){
Is not necessary call `getBooks()` here, directly use `this.books`

2020-04-23 00:41 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/User.java
> +        getBooks().add(book);
Same here

2020-04-23 00:41 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/User.java
> +    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
Here the relationships need to be REFRESH, PERSIST is ok

Persist says: If you persist the Users instance to the DB, then persist every item that this collection has in the DB as well.
Merge says: If you changed the in-memory values of the collection, then merge this changes to the DB so these are reflected there.
Refresh says: If something changed in the database values of the collection, then refresh those changes in the in-memory values.

2020-04-23 00:41 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/Book.java
> +    private List<User> users;
Initialize this like books in User model

2020-04-23 15:10 UTC, jhonmunoz commented on src/main/java/com/wolox/training/models/User.java
> +    @JoinTable(name = "book_user",
nice t know

2020-04-23 15:44 UTC, jhonmunoz commented on src/main/java/com/wolox/training/models/Book.java
> +    @ManyToMany(mappedBy = "books", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
Does it take the values from the User?

2020-04-23 16:37 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/User.java
> +    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
sorry my mistake the the relationships need to be REFRESH y MERGE

2020-04-23 16:38 UTC, rodrigofranc commented on src/main/java/com/wolox/training/models/Book.java
> +    @ManyToMany(mappedBy = "books", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
yes, JPA infers this 😁

2020-04-24 13:25 UTC, rodrigofranc approved these changes

2020-04-24 18:18 UTC, merged